// GENERATED by scripts/sync_remotion.py — registry of custom layer components (src/custom/<Name>.tsx).
import type React from "react";
import type { CustomLayerProps } from "../timeline-types";
import { ExampleBadge } from "./ExampleBadge";

export const registry: Record<string, React.FC<CustomLayerProps>> = {
  ExampleBadge,
};
