"""Sync timeline.json, media and agent-authored custom components into the Remotion template.

- src/data.ts          typed export of the timeline
- public/              every asset the timeline references (vo, bgm, sfx, cutouts, videos, lottie)
- src/custom/*.tsx     <run>/custom/*.tsx (storyboarder-written components) + regenerated registry index.ts
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path

from common import TEMPLATES, read_json, say

REMOTION = TEMPLATES / "remotion"
BUILTIN_CUSTOM = {"ExampleBadge"}


def referenced_assets(tl: dict) -> set[str]:
    refs = {"vo.mp3"}
    if tl.get("bgm"):
        refs.add(tl["bgm"]["src"])
    for hit in tl["sfx"]:
        refs.add(f"audio/{hit['name']}.mp3")
    for sc in tl["scenes"]:
        for layer in sc["layers"]:
            if layer["type"] in ("image", "video", "lottie", "waveform"):
                refs.add(layer["src"])
    return refs


def sync_custom(project: Path, remotion: Path, tl: dict) -> list[str]:
    """Copy <run>/custom/*.tsx into src/custom and rebuild the registry from every .tsx present."""
    dst_dir = remotion / "src" / "custom"
    dst_dir.mkdir(exist_ok=True)
    # drop components from previous runs (keep built-ins)
    for f in dst_dir.glob("*.tsx"):
        if f.stem not in BUILTIN_CUSTOM:
            f.unlink()
    src_dir = project / "custom"
    if src_dir.exists():
        for f in src_dir.glob("*.tsx"):
            if not re.fullmatch(r"[A-Z][A-Za-z0-9]*", f.stem):
                raise SystemExit(f"custom component file must be PascalCase: {f.name}")
            shutil.copy2(f, dst_dir / f.name)
    names = sorted(f.stem for f in dst_dir.glob("*.tsx"))
    needed = {l["component"] for sc in tl["scenes"] for l in sc["layers"] if l["type"] == "custom"}
    missing = needed - set(names)
    if missing:
        raise SystemExit(f"storyboard uses custom components without a file in <run>/custom/: {sorted(missing)}")
    lines = [
        "// GENERATED by scripts/sync_remotion.py — registry of custom layer components (src/custom/<Name>.tsx).",
        'import type React from "react";',
        'import type { CustomLayerProps } from "../timeline-types";',
        *[f'import {{ {n} }} from "./{n}";' for n in names],
        "",
        "export const registry: Record<string, React.FC<CustomLayerProps>> = {",
        *[f"  {n}," for n in names],
        "};",
        "",
    ]
    (dst_dir / "index.ts").write_text("\n".join(lines), encoding="utf-8")
    return names


def sync(project: Path, remotion: Path = REMOTION) -> dict:
    tl = read_json(project / "timeline.json")
    body = json.dumps(tl, ensure_ascii=False, indent=2)
    (remotion / "src" / "data.ts").write_text(
        "/* eslint-disable */\n"
        'import type { Timeline } from "./timeline-types";\n\n'
        "// GENERATED by scripts/sync_remotion.py from timeline.json — do not edit by hand.\n"
        f"export const timeline: Timeline = {body} as Timeline;\n",
        encoding="utf-8",
    )
    public = remotion / "public"
    if public.exists():
        shutil.rmtree(public)
    copied = 0
    for rel in sorted(referenced_assets(tl)):
        src = project / "assets" / rel
        if not src.exists():
            raise SystemExit(f"missing asset: {src}")
        dst = public / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        copied += 1
    customs = sync_custom(project, remotion, tl)
    return {"frames": round(tl["duration"] * tl["fps"]), "assets_copied": copied, "custom_components": customs}


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", required=True)
    args = ap.parse_args()
    say(sync(Path(args.project)))
